# Generated by Django 6.0.2 on 2026-03-21 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0001_initial'),
        ('personas', '0002_remove_persona_año_de_nacimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='personas.persona'),
        ),
    ]
