# Generated by Django 6.0.2 on 2026-03-06 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombres', models.CharField(max_length=100)),
                ('Año_de_Nacimiento', models.DateField()),
                ('Parentesco_Familiar', models.CharField(max_length=100)),
                ('Ocupacion', models.CharField(max_length=100)),
                ('Datos_medicos', models.CharField(max_length=100)),
                ('Ingreso_mensual', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
