# Generated by Django 6.0.2 on 2026-03-21 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='Año_de_Nacimiento',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='Datos_medicos',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='Ingreso_mensual',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='Ocupacion',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='Parentesco_Familiar',
        ),
        migrations.AddField(
            model_name='persona',
            name='edad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='gastos_mensuales',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='parentesco',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='persona',
            name='datos_medicos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='ingreso_mensual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='ocupacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
