# Generated by Django 6.0.2 on 2026-03-21 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_remove_persona_año_de_nacimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='datos_medicos',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
